/*
 * This file is generated by jOOQ.
*/
package com.taketoritei.order.jooq;


import com.taketoritei.order.jooq.tables.DCart;
import com.taketoritei.order.jooq.tables.DCartLang;
import com.taketoritei.order.jooq.tables.DDining;
import com.taketoritei.order.jooq.tables.DOrder;
import com.taketoritei.order.jooq.tables.DOrderLang;
import com.taketoritei.order.jooq.tables.MAdmin;
import com.taketoritei.order.jooq.tables.MDiningPlace;
import com.taketoritei.order.jooq.tables.MOmiyage;
import com.taketoritei.order.jooq.tables.MOmiyageLang;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>taketori</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index D_CART_PKEY = Indexes0.D_CART_PKEY;
    public static final Index D_CART_LANG_PKEY = Indexes0.D_CART_LANG_PKEY;
    public static final Index D_DINING_DAYS_ROOM_NO_KEY = Indexes0.D_DINING_DAYS_ROOM_NO_KEY;
    public static final Index D_DINING_PKEY = Indexes0.D_DINING_PKEY;
    public static final Index D_ORDER_PKEY = Indexes0.D_ORDER_PKEY;
    public static final Index D_ORDER_LANG_PKEY = Indexes0.D_ORDER_LANG_PKEY;
    public static final Index M_ADMIN_PKEY = Indexes0.M_ADMIN_PKEY;
    public static final Index M_DINING_PLACE_PKEY = Indexes0.M_DINING_PLACE_PKEY;
    public static final Index M_OMIYAGE_PKEY = Indexes0.M_OMIYAGE_PKEY;
    public static final Index M_OMIYAGE_LANG_PKEY = Indexes0.M_OMIYAGE_LANG_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index D_CART_PKEY = Internal.createIndex("d_cart_pkey", DCart.D_CART, new OrderField[] { DCart.D_CART.CART_ID }, true);
        public static Index D_CART_LANG_PKEY = Internal.createIndex("d_cart_lang_pkey", DCartLang.D_CART_LANG, new OrderField[] { DCartLang.D_CART_LANG.CART_ID, DCartLang.D_CART_LANG.LANGUAGE }, true);
        public static Index D_DINING_DAYS_ROOM_NO_KEY = Internal.createIndex("d_dining_days_room_no_key", DDining.D_DINING, new OrderField[] { DDining.D_DINING.DAYS, DDining.D_DINING.ROOM_NO }, true);
        public static Index D_DINING_PKEY = Internal.createIndex("d_dining_pkey", DDining.D_DINING, new OrderField[] { DDining.D_DINING.ID }, true);
        public static Index D_ORDER_PKEY = Internal.createIndex("d_order_pkey", DOrder.D_ORDER, new OrderField[] { DOrder.D_ORDER.ORDER_ID }, true);
        public static Index D_ORDER_LANG_PKEY = Internal.createIndex("d_order_lang_pkey", DOrderLang.D_ORDER_LANG, new OrderField[] { DOrderLang.D_ORDER_LANG.ORDER_ID, DOrderLang.D_ORDER_LANG.LANGUAGE }, true);
        public static Index M_ADMIN_PKEY = Internal.createIndex("m_admin_pkey", MAdmin.M_ADMIN, new OrderField[] { MAdmin.M_ADMIN.ADMIN_ID }, true);
        public static Index M_DINING_PLACE_PKEY = Internal.createIndex("m_dining_place_pkey", MDiningPlace.M_DINING_PLACE, new OrderField[] { MDiningPlace.M_DINING_PLACE.ID }, true);
        public static Index M_OMIYAGE_PKEY = Internal.createIndex("m_omiyage_pkey", MOmiyage.M_OMIYAGE, new OrderField[] { MOmiyage.M_OMIYAGE.OMIYAGE_ID }, true);
        public static Index M_OMIYAGE_LANG_PKEY = Internal.createIndex("m_omiyage_lang_pkey", MOmiyageLang.M_OMIYAGE_LANG, new OrderField[] { MOmiyageLang.M_OMIYAGE_LANG.OMIYAGE_ID, MOmiyageLang.M_OMIYAGE_LANG.LANGUAGE }, true);
    }
}
