/*
 * This file is generated by jOOQ.
*/
package com.taketoritei.order.jooq;


import com.taketoritei.order.jooq.tables.DCart;
import com.taketoritei.order.jooq.tables.DCartLang;
import com.taketoritei.order.jooq.tables.DDining;
import com.taketoritei.order.jooq.tables.DOrder;
import com.taketoritei.order.jooq.tables.DOrderLang;
import com.taketoritei.order.jooq.tables.MAdmin;
import com.taketoritei.order.jooq.tables.MDiningPlace;
import com.taketoritei.order.jooq.tables.MOmiyage;
import com.taketoritei.order.jooq.tables.MOmiyageLang;
import com.taketoritei.order.jooq.tables.records.DCartLangRecord;
import com.taketoritei.order.jooq.tables.records.DCartRecord;
import com.taketoritei.order.jooq.tables.records.DDiningRecord;
import com.taketoritei.order.jooq.tables.records.DOrderLangRecord;
import com.taketoritei.order.jooq.tables.records.DOrderRecord;
import com.taketoritei.order.jooq.tables.records.MAdminRecord;
import com.taketoritei.order.jooq.tables.records.MDiningPlaceRecord;
import com.taketoritei.order.jooq.tables.records.MOmiyageLangRecord;
import com.taketoritei.order.jooq.tables.records.MOmiyageRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>taketori</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<DCartRecord, Integer> IDENTITY_D_CART = Identities0.IDENTITY_D_CART;
    public static final Identity<DDiningRecord, Integer> IDENTITY_D_DINING = Identities0.IDENTITY_D_DINING;
    public static final Identity<DOrderRecord, Integer> IDENTITY_D_ORDER = Identities0.IDENTITY_D_ORDER;
    public static final Identity<MDiningPlaceRecord, Integer> IDENTITY_M_DINING_PLACE = Identities0.IDENTITY_M_DINING_PLACE;
    public static final Identity<MOmiyageRecord, Integer> IDENTITY_M_OMIYAGE = Identities0.IDENTITY_M_OMIYAGE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DCartRecord> D_CART_PKEY = UniqueKeys0.D_CART_PKEY;
    public static final UniqueKey<DCartLangRecord> D_CART_LANG_PKEY = UniqueKeys0.D_CART_LANG_PKEY;
    public static final UniqueKey<DDiningRecord> D_DINING_PKEY = UniqueKeys0.D_DINING_PKEY;
    public static final UniqueKey<DDiningRecord> D_DINING_DAYS_ROOM_NO_KEY = UniqueKeys0.D_DINING_DAYS_ROOM_NO_KEY;
    public static final UniqueKey<DOrderRecord> D_ORDER_PKEY = UniqueKeys0.D_ORDER_PKEY;
    public static final UniqueKey<DOrderLangRecord> D_ORDER_LANG_PKEY = UniqueKeys0.D_ORDER_LANG_PKEY;
    public static final UniqueKey<MAdminRecord> M_ADMIN_PKEY = UniqueKeys0.M_ADMIN_PKEY;
    public static final UniqueKey<MDiningPlaceRecord> M_DINING_PLACE_PKEY = UniqueKeys0.M_DINING_PLACE_PKEY;
    public static final UniqueKey<MOmiyageRecord> M_OMIYAGE_PKEY = UniqueKeys0.M_OMIYAGE_PKEY;
    public static final UniqueKey<MOmiyageLangRecord> M_OMIYAGE_LANG_PKEY = UniqueKeys0.M_OMIYAGE_LANG_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<DCartRecord, Integer> IDENTITY_D_CART = Internal.createIdentity(DCart.D_CART, DCart.D_CART.CART_ID);
        public static Identity<DDiningRecord, Integer> IDENTITY_D_DINING = Internal.createIdentity(DDining.D_DINING, DDining.D_DINING.ID);
        public static Identity<DOrderRecord, Integer> IDENTITY_D_ORDER = Internal.createIdentity(DOrder.D_ORDER, DOrder.D_ORDER.ORDER_ID);
        public static Identity<MDiningPlaceRecord, Integer> IDENTITY_M_DINING_PLACE = Internal.createIdentity(MDiningPlace.M_DINING_PLACE, MDiningPlace.M_DINING_PLACE.ID);
        public static Identity<MOmiyageRecord, Integer> IDENTITY_M_OMIYAGE = Internal.createIdentity(MOmiyage.M_OMIYAGE, MOmiyage.M_OMIYAGE.OMIYAGE_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<DCartRecord> D_CART_PKEY = Internal.createUniqueKey(DCart.D_CART, "d_cart_pkey", DCart.D_CART.CART_ID);
        public static final UniqueKey<DCartLangRecord> D_CART_LANG_PKEY = Internal.createUniqueKey(DCartLang.D_CART_LANG, "d_cart_lang_pkey", DCartLang.D_CART_LANG.CART_ID, DCartLang.D_CART_LANG.LANGUAGE);
        public static final UniqueKey<DDiningRecord> D_DINING_PKEY = Internal.createUniqueKey(DDining.D_DINING, "d_dining_pkey", DDining.D_DINING.ID);
        public static final UniqueKey<DDiningRecord> D_DINING_DAYS_ROOM_NO_KEY = Internal.createUniqueKey(DDining.D_DINING, "d_dining_days_room_no_key", DDining.D_DINING.DAYS, DDining.D_DINING.ROOM_NO);
        public static final UniqueKey<DOrderRecord> D_ORDER_PKEY = Internal.createUniqueKey(DOrder.D_ORDER, "d_order_pkey", DOrder.D_ORDER.ORDER_ID);
        public static final UniqueKey<DOrderLangRecord> D_ORDER_LANG_PKEY = Internal.createUniqueKey(DOrderLang.D_ORDER_LANG, "d_order_lang_pkey", DOrderLang.D_ORDER_LANG.ORDER_ID, DOrderLang.D_ORDER_LANG.LANGUAGE);
        public static final UniqueKey<MAdminRecord> M_ADMIN_PKEY = Internal.createUniqueKey(MAdmin.M_ADMIN, "m_admin_pkey", MAdmin.M_ADMIN.ADMIN_ID);
        public static final UniqueKey<MDiningPlaceRecord> M_DINING_PLACE_PKEY = Internal.createUniqueKey(MDiningPlace.M_DINING_PLACE, "m_dining_place_pkey", MDiningPlace.M_DINING_PLACE.ID);
        public static final UniqueKey<MOmiyageRecord> M_OMIYAGE_PKEY = Internal.createUniqueKey(MOmiyage.M_OMIYAGE, "m_omiyage_pkey", MOmiyage.M_OMIYAGE.OMIYAGE_ID);
        public static final UniqueKey<MOmiyageLangRecord> M_OMIYAGE_LANG_PKEY = Internal.createUniqueKey(MOmiyageLang.M_OMIYAGE_LANG, "m_omiyage_lang_pkey", MOmiyageLang.M_OMIYAGE_LANG.OMIYAGE_ID, MOmiyageLang.M_OMIYAGE_LANG.LANGUAGE);
    }
}
