/*
 * This file is generated by jOOQ.
*/
package com.taketoritei.order.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in taketori
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>taketori.d_cart_cart_id_seq</code>
     */
    public static final Sequence<Integer> D_CART_CART_ID_SEQ = new SequenceImpl<Integer>("d_cart_cart_id_seq", Taketori.TAKETORI, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>taketori.d_dining_id_seq</code>
     */
    public static final Sequence<Integer> D_DINING_ID_SEQ = new SequenceImpl<Integer>("d_dining_id_seq", Taketori.TAKETORI, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>taketori.d_order_order_id_seq</code>
     */
    public static final Sequence<Integer> D_ORDER_ORDER_ID_SEQ = new SequenceImpl<Integer>("d_order_order_id_seq", Taketori.TAKETORI, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>taketori.m_dining_place_id_seq</code>
     */
    public static final Sequence<Integer> M_DINING_PLACE_ID_SEQ = new SequenceImpl<Integer>("m_dining_place_id_seq", Taketori.TAKETORI, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>taketori.m_omiyage_omiyage_id_seq</code>
     */
    public static final Sequence<Integer> M_OMIYAGE_OMIYAGE_ID_SEQ = new SequenceImpl<Integer>("m_omiyage_omiyage_id_seq", Taketori.TAKETORI, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
