/*
 * This file is generated by jOOQ.
*/
package com.taketoritei.order.jooq;


import com.taketoritei.order.jooq.tables.DCart;
import com.taketoritei.order.jooq.tables.DCartLang;
import com.taketoritei.order.jooq.tables.DDining;
import com.taketoritei.order.jooq.tables.DDiningMessage;
import com.taketoritei.order.jooq.tables.DOrder;
import com.taketoritei.order.jooq.tables.DOrderLang;
import com.taketoritei.order.jooq.tables.DReserveBath;
import com.taketoritei.order.jooq.tables.MAdmin;
import com.taketoritei.order.jooq.tables.MDiningPlace;
import com.taketoritei.order.jooq.tables.MOmiyage;
import com.taketoritei.order.jooq.tables.MOmiyageLang;
import com.taketoritei.order.jooq.tables.MRoom;
import com.taketoritei.order.jooq.tables.MTime;
import com.taketoritei.order.jooq.tables.MTimeBk;
import com.taketoritei.order.jooq.tables.MUser;
import com.taketoritei.order.jooq.tables.VdCart;
import com.taketoritei.order.jooq.tables.VdOrder;
import com.taketoritei.order.jooq.tables.VmOmiyage;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in taketori
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>taketori.d_cart</code>.
     */
    public static final DCart D_CART = com.taketoritei.order.jooq.tables.DCart.D_CART;

    /**
     * The table <code>taketori.d_cart_lang</code>.
     */
    public static final DCartLang D_CART_LANG = com.taketoritei.order.jooq.tables.DCartLang.D_CART_LANG;

    /**
     * The table <code>taketori.d_dining</code>.
     */
    public static final DDining D_DINING = com.taketoritei.order.jooq.tables.DDining.D_DINING;

    /**
     * The table <code>taketori.d_dining_message</code>.
     */
    public static final DDiningMessage D_DINING_MESSAGE = com.taketoritei.order.jooq.tables.DDiningMessage.D_DINING_MESSAGE;

    /**
     * The table <code>taketori.d_order</code>.
     */
    public static final DOrder D_ORDER = com.taketoritei.order.jooq.tables.DOrder.D_ORDER;

    /**
     * The table <code>taketori.d_order_lang</code>.
     */
    public static final DOrderLang D_ORDER_LANG = com.taketoritei.order.jooq.tables.DOrderLang.D_ORDER_LANG;

    /**
     * The table <code>taketori.d_reserve_bath</code>.
     */
    public static final DReserveBath D_RESERVE_BATH = com.taketoritei.order.jooq.tables.DReserveBath.D_RESERVE_BATH;

    /**
     * The table <code>taketori.m_admin</code>.
     */
    public static final MAdmin M_ADMIN = com.taketoritei.order.jooq.tables.MAdmin.M_ADMIN;

    /**
     * The table <code>taketori.m_dining_place</code>.
     */
    public static final MDiningPlace M_DINING_PLACE = com.taketoritei.order.jooq.tables.MDiningPlace.M_DINING_PLACE;

    /**
     * The table <code>taketori.m_omiyage</code>.
     */
    public static final MOmiyage M_OMIYAGE = com.taketoritei.order.jooq.tables.MOmiyage.M_OMIYAGE;

    /**
     * The table <code>taketori.m_omiyage_lang</code>.
     */
    public static final MOmiyageLang M_OMIYAGE_LANG = com.taketoritei.order.jooq.tables.MOmiyageLang.M_OMIYAGE_LANG;

    /**
     * The table <code>taketori.m_room</code>.
     */
    public static final MRoom M_ROOM = com.taketoritei.order.jooq.tables.MRoom.M_ROOM;

    /**
     * The table <code>taketori.m_time</code>.
     */
    public static final MTime M_TIME = com.taketoritei.order.jooq.tables.MTime.M_TIME;

    /**
     * The table <code>taketori.m_time_bk</code>.
     */
    public static final MTimeBk M_TIME_BK = com.taketoritei.order.jooq.tables.MTimeBk.M_TIME_BK;

    /**
     * The table <code>taketori.m_user</code>.
     */
    public static final MUser M_USER = com.taketoritei.order.jooq.tables.MUser.M_USER;

    /**
     * The table <code>taketori.vd_cart</code>.
     */
    public static final VdCart VD_CART = com.taketoritei.order.jooq.tables.VdCart.VD_CART;

    /**
     * The table <code>taketori.vd_order</code>.
     */
    public static final VdOrder VD_ORDER = com.taketoritei.order.jooq.tables.VdOrder.VD_ORDER;

    /**
     * The table <code>taketori.vm_omiyage</code>.
     */
    public static final VmOmiyage VM_OMIYAGE = com.taketoritei.order.jooq.tables.VmOmiyage.VM_OMIYAGE;
}
