/*
 * This file is generated by jOOQ.
*/
package com.taketoritei.order.jooq;


import com.taketoritei.order.jooq.tables.DCart;
import com.taketoritei.order.jooq.tables.DCartLang;
import com.taketoritei.order.jooq.tables.DDining;
import com.taketoritei.order.jooq.tables.DDiningMessage;
import com.taketoritei.order.jooq.tables.DOrder;
import com.taketoritei.order.jooq.tables.DOrderLang;
import com.taketoritei.order.jooq.tables.DReserveBath;
import com.taketoritei.order.jooq.tables.MAdmin;
import com.taketoritei.order.jooq.tables.MDiningPlace;
import com.taketoritei.order.jooq.tables.MOmiyage;
import com.taketoritei.order.jooq.tables.MOmiyageLang;
import com.taketoritei.order.jooq.tables.MRoom;
import com.taketoritei.order.jooq.tables.MTime;
import com.taketoritei.order.jooq.tables.MTimeBk;
import com.taketoritei.order.jooq.tables.MUser;
import com.taketoritei.order.jooq.tables.VdCart;
import com.taketoritei.order.jooq.tables.VdOrder;
import com.taketoritei.order.jooq.tables.VmOmiyage;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Taketori extends SchemaImpl {

    private static final long serialVersionUID = -559309496;

    /**
     * The reference instance of <code>taketori</code>
     */
    public static final Taketori TAKETORI = new Taketori();

    /**
     * The table <code>taketori.d_cart</code>.
     */
    public final DCart D_CART = com.taketoritei.order.jooq.tables.DCart.D_CART;

    /**
     * The table <code>taketori.d_cart_lang</code>.
     */
    public final DCartLang D_CART_LANG = com.taketoritei.order.jooq.tables.DCartLang.D_CART_LANG;

    /**
     * The table <code>taketori.d_dining</code>.
     */
    public final DDining D_DINING = com.taketoritei.order.jooq.tables.DDining.D_DINING;

    /**
     * The table <code>taketori.d_dining_message</code>.
     */
    public final DDiningMessage D_DINING_MESSAGE = com.taketoritei.order.jooq.tables.DDiningMessage.D_DINING_MESSAGE;

    /**
     * The table <code>taketori.d_order</code>.
     */
    public final DOrder D_ORDER = com.taketoritei.order.jooq.tables.DOrder.D_ORDER;

    /**
     * The table <code>taketori.d_order_lang</code>.
     */
    public final DOrderLang D_ORDER_LANG = com.taketoritei.order.jooq.tables.DOrderLang.D_ORDER_LANG;

    /**
     * The table <code>taketori.d_reserve_bath</code>.
     */
    public final DReserveBath D_RESERVE_BATH = com.taketoritei.order.jooq.tables.DReserveBath.D_RESERVE_BATH;

    /**
     * The table <code>taketori.m_admin</code>.
     */
    public final MAdmin M_ADMIN = com.taketoritei.order.jooq.tables.MAdmin.M_ADMIN;

    /**
     * The table <code>taketori.m_dining_place</code>.
     */
    public final MDiningPlace M_DINING_PLACE = com.taketoritei.order.jooq.tables.MDiningPlace.M_DINING_PLACE;

    /**
     * The table <code>taketori.m_omiyage</code>.
     */
    public final MOmiyage M_OMIYAGE = com.taketoritei.order.jooq.tables.MOmiyage.M_OMIYAGE;

    /**
     * The table <code>taketori.m_omiyage_lang</code>.
     */
    public final MOmiyageLang M_OMIYAGE_LANG = com.taketoritei.order.jooq.tables.MOmiyageLang.M_OMIYAGE_LANG;

    /**
     * The table <code>taketori.m_room</code>.
     */
    public final MRoom M_ROOM = com.taketoritei.order.jooq.tables.MRoom.M_ROOM;

    /**
     * The table <code>taketori.m_time</code>.
     */
    public final MTime M_TIME = com.taketoritei.order.jooq.tables.MTime.M_TIME;

    /**
     * The table <code>taketori.m_time_bk</code>.
     */
    public final MTimeBk M_TIME_BK = com.taketoritei.order.jooq.tables.MTimeBk.M_TIME_BK;

    /**
     * The table <code>taketori.m_user</code>.
     */
    public final MUser M_USER = com.taketoritei.order.jooq.tables.MUser.M_USER;

    /**
     * The table <code>taketori.vd_cart</code>.
     */
    public final VdCart VD_CART = com.taketoritei.order.jooq.tables.VdCart.VD_CART;

    /**
     * The table <code>taketori.vd_order</code>.
     */
    public final VdOrder VD_ORDER = com.taketoritei.order.jooq.tables.VdOrder.VD_ORDER;

    /**
     * The table <code>taketori.vm_omiyage</code>.
     */
    public final VmOmiyage VM_OMIYAGE = com.taketoritei.order.jooq.tables.VmOmiyage.VM_OMIYAGE;

    /**
     * No further instances allowed
     */
    private Taketori() {
        super("taketori", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.D_CART_CART_ID_SEQ,
            Sequences.D_DINING_ID_SEQ,
            Sequences.D_ORDER_ORDER_ID_SEQ,
            Sequences.M_DINING_PLACE_ID_SEQ,
            Sequences.M_OMIYAGE_OMIYAGE_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            DCart.D_CART,
            DCartLang.D_CART_LANG,
            DDining.D_DINING,
            DDiningMessage.D_DINING_MESSAGE,
            DOrder.D_ORDER,
            DOrderLang.D_ORDER_LANG,
            DReserveBath.D_RESERVE_BATH,
            MAdmin.M_ADMIN,
            MDiningPlace.M_DINING_PLACE,
            MOmiyage.M_OMIYAGE,
            MOmiyageLang.M_OMIYAGE_LANG,
            MRoom.M_ROOM,
            MTime.M_TIME,
            MTimeBk.M_TIME_BK,
            MUser.M_USER,
            VdCart.VD_CART,
            VdOrder.VD_ORDER,
            VmOmiyage.VM_OMIYAGE);
    }
}
