/*
 * This file is generated by jOOQ.
*/
package com.taketoritei.order.jooq.tables.records;


import com.taketoritei.order.jooq.tables.DCart;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DCartRecord extends UpdatableRecordImpl<DCartRecord> implements Record9<Integer, String, Integer, Integer, Integer, String, Boolean, Timestamp, String> {

    private static final long serialVersionUID = -1588870833;

    /**
     * Setter for <code>taketori.d_cart.cart_id</code>.
     */
    public void setCartId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>taketori.d_cart.cart_id</code>.
     */
    public Integer getCartId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>taketori.d_cart.token</code>.
     */
    public void setToken(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>taketori.d_cart.token</code>.
     */
    public String getToken() {
        return (String) get(1);
    }

    /**
     * Setter for <code>taketori.d_cart.omiyage_id</code>.
     */
    public void setOmiyageId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>taketori.d_cart.omiyage_id</code>.
     */
    public Integer getOmiyageId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>taketori.d_cart.price</code>.
     */
    public void setPrice(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>taketori.d_cart.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>taketori.d_cart.num</code>.
     */
    public void setNum(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>taketori.d_cart.num</code>.
     */
    public Integer getNum() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>taketori.d_cart.cart_token</code>.
     */
    public void setCartToken(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>taketori.d_cart.cart_token</code>.
     */
    public String getCartToken() {
        return (String) get(5);
    }

    /**
     * Setter for <code>taketori.d_cart.del_flg</code>.
     */
    public void setDelFlg(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>taketori.d_cart.del_flg</code>.
     */
    public Boolean getDelFlg() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>taketori.d_cart.last_date</code>.
     */
    public void setLastDate(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>taketori.d_cart.last_date</code>.
     */
    public Timestamp getLastDate() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>taketori.d_cart.last_user</code>.
     */
    public void setLastUser(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>taketori.d_cart.last_user</code>.
     */
    public String getLastUser() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, Integer, Integer, Integer, String, Boolean, Timestamp, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, Integer, Integer, Integer, String, Boolean, Timestamp, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DCart.D_CART.CART_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DCart.D_CART.TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return DCart.D_CART.OMIYAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return DCart.D_CART.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return DCart.D_CART.NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return DCart.D_CART.CART_TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return DCart.D_CART.DEL_FLG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return DCart.D_CART.LAST_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return DCart.D_CART.LAST_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getCartId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getOmiyageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCartToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component7() {
        return getDelFlg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getLastDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getLastUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCartId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getOmiyageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCartToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getDelFlg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getLastDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getLastUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DCartRecord value1(Integer value) {
        setCartId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DCartRecord value2(String value) {
        setToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DCartRecord value3(Integer value) {
        setOmiyageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DCartRecord value4(Integer value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DCartRecord value5(Integer value) {
        setNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DCartRecord value6(String value) {
        setCartToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DCartRecord value7(Boolean value) {
        setDelFlg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DCartRecord value8(Timestamp value) {
        setLastDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DCartRecord value9(String value) {
        setLastUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DCartRecord values(Integer value1, String value2, Integer value3, Integer value4, Integer value5, String value6, Boolean value7, Timestamp value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DCartRecord
     */
    public DCartRecord() {
        super(DCart.D_CART);
    }

    /**
     * Create a detached, initialised DCartRecord
     */
    public DCartRecord(Integer cartId, String token, Integer omiyageId, Integer price, Integer num, String cartToken, Boolean delFlg, Timestamp lastDate, String lastUser) {
        super(DCart.D_CART);

        set(0, cartId);
        set(1, token);
        set(2, omiyageId);
        set(3, price);
        set(4, num);
        set(5, cartToken);
        set(6, delFlg);
        set(7, lastDate);
        set(8, lastUser);
    }
}
