/*
 * This file is generated by jOOQ.
*/
package com.taketoritei.order.jooq.tables.records;


import com.taketoritei.order.jooq.tables.DDining;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DDiningRecord extends UpdatableRecordImpl<DDiningRecord> implements Record14<Integer, Date, String, Integer, String, String, String, Integer, Integer, String, String, Integer, String, String> {

    private static final long serialVersionUID = 1902992508;

    /**
     * Setter for <code>taketori.d_dining.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>taketori.d_dining.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>taketori.d_dining.days</code>.
     */
    public void setDays(Date value) {
        set(1, value);
    }

    /**
     * Getter for <code>taketori.d_dining.days</code>.
     */
    public Date getDays() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>taketori.d_dining.room_no</code>.
     */
    public void setRoomNo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>taketori.d_dining.room_no</code>.
     */
    public String getRoomNo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>taketori.d_dining.customer_num</code>.
     */
    public void setCustomerNum(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>taketori.d_dining.customer_num</code>.
     */
    public Integer getCustomerNum() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>taketori.d_dining.dinner</code>.
     */
    public void setDinner(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>taketori.d_dining.dinner</code>.
     */
    public String getDinner() {
        return (String) get(4);
    }

    /**
     * Setter for <code>taketori.d_dining.dinner_time</code>.
     */
    public void setDinnerTime(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>taketori.d_dining.dinner_time</code>.
     */
    public String getDinnerTime() {
        return (String) get(5);
    }

    /**
     * Setter for <code>taketori.d_dining.dinner_place</code>.
     */
    public void setDinnerPlace(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>taketori.d_dining.dinner_place</code>.
     */
    public String getDinnerPlace() {
        return (String) get(6);
    }

    /**
     * Setter for <code>taketori.d_dining.breakfast_japanese</code>.
     */
    public void setBreakfastJapanese(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>taketori.d_dining.breakfast_japanese</code>.
     */
    public Integer getBreakfastJapanese() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>taketori.d_dining.breakfast_western</code>.
     */
    public void setBreakfastWestern(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>taketori.d_dining.breakfast_western</code>.
     */
    public Integer getBreakfastWestern() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>taketori.d_dining.breakfast_time</code>.
     */
    public void setBreakfastTime(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>taketori.d_dining.breakfast_time</code>.
     */
    public String getBreakfastTime() {
        return (String) get(9);
    }

    /**
     * Setter for <code>taketori.d_dining.breakfast_place</code>.
     */
    public void setBreakfastPlace(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>taketori.d_dining.breakfast_place</code>.
     */
    public String getBreakfastPlace() {
        return (String) get(10);
    }

    /**
     * Setter for <code>taketori.d_dining.lunch_num</code>.
     */
    public void setLunchNum(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>taketori.d_dining.lunch_num</code>.
     */
    public Integer getLunchNum() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>taketori.d_dining.lunch_time</code>.
     */
    public void setLunchTime(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>taketori.d_dining.lunch_time</code>.
     */
    public String getLunchTime() {
        return (String) get(12);
    }

    /**
     * Setter for <code>taketori.d_dining.memo</code>.
     */
    public void setMemo(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>taketori.d_dining.memo</code>.
     */
    public String getMemo() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, Date, String, Integer, String, String, String, Integer, Integer, String, String, Integer, String, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, Date, String, Integer, String, String, String, Integer, Integer, String, String, Integer, String, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DDining.D_DINING.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return DDining.D_DINING.DAYS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DDining.D_DINING.ROOM_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return DDining.D_DINING.CUSTOMER_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return DDining.D_DINING.DINNER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return DDining.D_DINING.DINNER_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return DDining.D_DINING.DINNER_PLACE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return DDining.D_DINING.BREAKFAST_JAPANESE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return DDining.D_DINING.BREAKFAST_WESTERN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return DDining.D_DINING.BREAKFAST_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return DDining.D_DINING.BREAKFAST_PLACE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return DDining.D_DINING.LUNCH_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return DDining.D_DINING.LUNCH_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return DDining.D_DINING.MEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component2() {
        return getDays();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getRoomNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getCustomerNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDinner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getDinnerTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getDinnerPlace();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getBreakfastJapanese();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getBreakfastWestern();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getBreakfastTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getBreakfastPlace();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component12() {
        return getLunchNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getLunchTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getDays();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRoomNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCustomerNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDinner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDinnerTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDinnerPlace();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getBreakfastJapanese();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getBreakfastWestern();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getBreakfastTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getBreakfastPlace();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getLunchNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getLunchTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DDiningRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DDiningRecord value2(Date value) {
        setDays(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DDiningRecord value3(String value) {
        setRoomNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DDiningRecord value4(Integer value) {
        setCustomerNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DDiningRecord value5(String value) {
        setDinner(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DDiningRecord value6(String value) {
        setDinnerTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DDiningRecord value7(String value) {
        setDinnerPlace(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DDiningRecord value8(Integer value) {
        setBreakfastJapanese(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DDiningRecord value9(Integer value) {
        setBreakfastWestern(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DDiningRecord value10(String value) {
        setBreakfastTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DDiningRecord value11(String value) {
        setBreakfastPlace(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DDiningRecord value12(Integer value) {
        setLunchNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DDiningRecord value13(String value) {
        setLunchTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DDiningRecord value14(String value) {
        setMemo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DDiningRecord values(Integer value1, Date value2, String value3, Integer value4, String value5, String value6, String value7, Integer value8, Integer value9, String value10, String value11, Integer value12, String value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DDiningRecord
     */
    public DDiningRecord() {
        super(DDining.D_DINING);
    }

    /**
     * Create a detached, initialised DDiningRecord
     */
    public DDiningRecord(Integer id, Date days, String roomNo, Integer customerNum, String dinner, String dinnerTime, String dinnerPlace, Integer breakfastJapanese, Integer breakfastWestern, String breakfastTime, String breakfastPlace, Integer lunchNum, String lunchTime, String memo) {
        super(DDining.D_DINING);

        set(0, id);
        set(1, days);
        set(2, roomNo);
        set(3, customerNum);
        set(4, dinner);
        set(5, dinnerTime);
        set(6, dinnerPlace);
        set(7, breakfastJapanese);
        set(8, breakfastWestern);
        set(9, breakfastTime);
        set(10, breakfastPlace);
        set(11, lunchNum);
        set(12, lunchTime);
        set(13, memo);
    }
}
