/*
 * This file is generated by jOOQ.
*/
package com.taketoritei.order.jooq.tables.records;


import com.taketoritei.order.jooq.tables.DOrder;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DOrderRecord extends UpdatableRecordImpl<DOrderRecord> implements Record8<Integer, String, Integer, Integer, Integer, Boolean, Timestamp, String> {

    private static final long serialVersionUID = -1131403184;

    /**
     * Setter for <code>taketori.d_order.order_id</code>.
     */
    public void setOrderId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>taketori.d_order.order_id</code>.
     */
    public Integer getOrderId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>taketori.d_order.token</code>.
     */
    public void setToken(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>taketori.d_order.token</code>.
     */
    public String getToken() {
        return (String) get(1);
    }

    /**
     * Setter for <code>taketori.d_order.omiyage_id</code>.
     */
    public void setOmiyageId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>taketori.d_order.omiyage_id</code>.
     */
    public Integer getOmiyageId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>taketori.d_order.price</code>.
     */
    public void setPrice(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>taketori.d_order.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>taketori.d_order.num</code>.
     */
    public void setNum(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>taketori.d_order.num</code>.
     */
    public Integer getNum() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>taketori.d_order.del_flg</code>.
     */
    public void setDelFlg(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>taketori.d_order.del_flg</code>.
     */
    public Boolean getDelFlg() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>taketori.d_order.last_date</code>.
     */
    public void setLastDate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>taketori.d_order.last_date</code>.
     */
    public Timestamp getLastDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>taketori.d_order.last_user</code>.
     */
    public void setLastUser(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>taketori.d_order.last_user</code>.
     */
    public String getLastUser() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Integer, Integer, Integer, Boolean, Timestamp, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Integer, Integer, Integer, Boolean, Timestamp, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DOrder.D_ORDER.ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DOrder.D_ORDER.TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return DOrder.D_ORDER.OMIYAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return DOrder.D_ORDER.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return DOrder.D_ORDER.NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return DOrder.D_ORDER.DEL_FLG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return DOrder.D_ORDER.LAST_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return DOrder.D_ORDER.LAST_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getOmiyageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component6() {
        return getDelFlg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getLastDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getLastUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getOmiyageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getDelFlg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getLastDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getLastUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderRecord value1(Integer value) {
        setOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderRecord value2(String value) {
        setToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderRecord value3(Integer value) {
        setOmiyageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderRecord value4(Integer value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderRecord value5(Integer value) {
        setNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderRecord value6(Boolean value) {
        setDelFlg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderRecord value7(Timestamp value) {
        setLastDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderRecord value8(String value) {
        setLastUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderRecord values(Integer value1, String value2, Integer value3, Integer value4, Integer value5, Boolean value6, Timestamp value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DOrderRecord
     */
    public DOrderRecord() {
        super(DOrder.D_ORDER);
    }

    /**
     * Create a detached, initialised DOrderRecord
     */
    public DOrderRecord(Integer orderId, String token, Integer omiyageId, Integer price, Integer num, Boolean delFlg, Timestamp lastDate, String lastUser) {
        super(DOrder.D_ORDER);

        set(0, orderId);
        set(1, token);
        set(2, omiyageId);
        set(3, price);
        set(4, num);
        set(5, delFlg);
        set(6, lastDate);
        set(7, lastUser);
    }
}
