/*
 * This file is generated by jOOQ.
*/
package com.taketoritei.order.jooq.tables.records;


import com.taketoritei.order.jooq.tables.DReserveBath;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DReserveBathRecord extends TableRecordImpl<DReserveBathRecord> implements Record9<String, String, String, String, Boolean, Timestamp, String, Integer, String> {

    private static final long serialVersionUID = -1630700578;

    /**
     * Setter for <code>taketori.d_reserve_bath.reserve_date</code>.
     */
    public void setReserveDate(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>taketori.d_reserve_bath.reserve_date</code>.
     */
    public String getReserveDate() {
        return (String) get(0);
    }

    /**
     * Setter for <code>taketori.d_reserve_bath.time_cd</code>.
     */
    public void setTimeCd(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>taketori.d_reserve_bath.time_cd</code>.
     */
    public String getTimeCd() {
        return (String) get(1);
    }

    /**
     * Setter for <code>taketori.d_reserve_bath.bath_cd</code>.
     */
    public void setBathCd(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>taketori.d_reserve_bath.bath_cd</code>.
     */
    public String getBathCd() {
        return (String) get(2);
    }

    /**
     * Setter for <code>taketori.d_reserve_bath.room_no</code>.
     */
    public void setRoomNo(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>taketori.d_reserve_bath.room_no</code>.
     */
    public String getRoomNo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>taketori.d_reserve_bath.del_flg</code>.
     */
    public void setDelFlg(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>taketori.d_reserve_bath.del_flg</code>.
     */
    public Boolean getDelFlg() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>taketori.d_reserve_bath.last_date</code>.
     */
    public void setLastDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>taketori.d_reserve_bath.last_date</code>.
     */
    public Timestamp getLastDate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>taketori.d_reserve_bath.last_user</code>.
     */
    public void setLastUser(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>taketori.d_reserve_bath.last_user</code>.
     */
    public String getLastUser() {
        return (String) get(6);
    }

    /**
     * Setter for <code>taketori.d_reserve_bath.reserve_count</code>.
     */
    public void setReserveCount(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>taketori.d_reserve_bath.reserve_count</code>.
     */
    public Integer getReserveCount() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>taketori.d_reserve_bath.token</code>.
     */
    public void setToken(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>taketori.d_reserve_bath.token</code>.
     */
    public String getToken() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, String, Boolean, Timestamp, String, Integer, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, String, Boolean, Timestamp, String, Integer, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return DReserveBath.D_RESERVE_BATH.RESERVE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DReserveBath.D_RESERVE_BATH.TIME_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DReserveBath.D_RESERVE_BATH.BATH_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return DReserveBath.D_RESERVE_BATH.ROOM_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return DReserveBath.D_RESERVE_BATH.DEL_FLG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return DReserveBath.D_RESERVE_BATH.LAST_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return DReserveBath.D_RESERVE_BATH.LAST_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return DReserveBath.D_RESERVE_BATH.RESERVE_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return DReserveBath.D_RESERVE_BATH.TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getReserveDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTimeCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getBathCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getRoomNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getDelFlg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getLastDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getLastUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getReserveCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getReserveDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTimeCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getBathCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRoomNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getDelFlg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getLastDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getLastUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getReserveCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DReserveBathRecord value1(String value) {
        setReserveDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DReserveBathRecord value2(String value) {
        setTimeCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DReserveBathRecord value3(String value) {
        setBathCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DReserveBathRecord value4(String value) {
        setRoomNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DReserveBathRecord value5(Boolean value) {
        setDelFlg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DReserveBathRecord value6(Timestamp value) {
        setLastDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DReserveBathRecord value7(String value) {
        setLastUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DReserveBathRecord value8(Integer value) {
        setReserveCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DReserveBathRecord value9(String value) {
        setToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DReserveBathRecord values(String value1, String value2, String value3, String value4, Boolean value5, Timestamp value6, String value7, Integer value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DReserveBathRecord
     */
    public DReserveBathRecord() {
        super(DReserveBath.D_RESERVE_BATH);
    }

    /**
     * Create a detached, initialised DReserveBathRecord
     */
    public DReserveBathRecord(String reserveDate, String timeCd, String bathCd, String roomNo, Boolean delFlg, Timestamp lastDate, String lastUser, Integer reserveCount, String token) {
        super(DReserveBath.D_RESERVE_BATH);

        set(0, reserveDate);
        set(1, timeCd);
        set(2, bathCd);
        set(3, roomNo);
        set(4, delFlg);
        set(5, lastDate);
        set(6, lastUser);
        set(7, reserveCount);
        set(8, token);
    }
}
