/*
 * This file is generated by jOOQ.
*/
package com.taketoritei.order.jooq.tables.records;


import com.taketoritei.order.jooq.tables.MAdmin;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MAdminRecord extends UpdatableRecordImpl<MAdminRecord> implements Record7<String, String, String, String, Boolean, Timestamp, String> {

    private static final long serialVersionUID = 131348787;

    /**
     * Setter for <code>taketori.m_admin.admin_id</code>.
     */
    public void setAdminId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>taketori.m_admin.admin_id</code>.
     */
    public String getAdminId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>taketori.m_admin.password</code>.
     */
    public void setPassword(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>taketori.m_admin.password</code>.
     */
    public String getPassword() {
        return (String) get(1);
    }

    /**
     * Setter for <code>taketori.m_admin.role</code>.
     */
    public void setRole(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>taketori.m_admin.role</code>.
     */
    public String getRole() {
        return (String) get(2);
    }

    /**
     * Setter for <code>taketori.m_admin.admin_name</code>.
     */
    public void setAdminName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>taketori.m_admin.admin_name</code>.
     */
    public String getAdminName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>taketori.m_admin.del_flg</code>.
     */
    public void setDelFlg(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>taketori.m_admin.del_flg</code>.
     */
    public Boolean getDelFlg() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>taketori.m_admin.last_date</code>.
     */
    public void setLastDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>taketori.m_admin.last_date</code>.
     */
    public Timestamp getLastDate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>taketori.m_admin.last_user</code>.
     */
    public void setLastUser(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>taketori.m_admin.last_user</code>.
     */
    public String getLastUser() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, Boolean, Timestamp, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, Boolean, Timestamp, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return MAdmin.M_ADMIN.ADMIN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MAdmin.M_ADMIN.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MAdmin.M_ADMIN.ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return MAdmin.M_ADMIN.ADMIN_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return MAdmin.M_ADMIN.DEL_FLG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return MAdmin.M_ADMIN.LAST_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return MAdmin.M_ADMIN.LAST_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getAdminId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAdminName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getDelFlg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getLastDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getLastUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getAdminId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAdminName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getDelFlg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getLastDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getLastUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MAdminRecord value1(String value) {
        setAdminId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MAdminRecord value2(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MAdminRecord value3(String value) {
        setRole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MAdminRecord value4(String value) {
        setAdminName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MAdminRecord value5(Boolean value) {
        setDelFlg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MAdminRecord value6(Timestamp value) {
        setLastDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MAdminRecord value7(String value) {
        setLastUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MAdminRecord values(String value1, String value2, String value3, String value4, Boolean value5, Timestamp value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MAdminRecord
     */
    public MAdminRecord() {
        super(MAdmin.M_ADMIN);
    }

    /**
     * Create a detached, initialised MAdminRecord
     */
    public MAdminRecord(String adminId, String password, String role, String adminName, Boolean delFlg, Timestamp lastDate, String lastUser) {
        super(MAdmin.M_ADMIN);

        set(0, adminId);
        set(1, password);
        set(2, role);
        set(3, adminName);
        set(4, delFlg);
        set(5, lastDate);
        set(6, lastUser);
    }
}
