/*
 * This file is generated by jOOQ.
*/
package com.taketoritei.order.jooq.tables.records;


import com.taketoritei.order.jooq.tables.MOmiyageLang;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MOmiyageLangRecord extends UpdatableRecordImpl<MOmiyageLangRecord> implements Record8<Integer, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -477692924;

    /**
     * Setter for <code>taketori.m_omiyage_lang.omiyage_id</code>.
     */
    public void setOmiyageId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>taketori.m_omiyage_lang.omiyage_id</code>.
     */
    public Integer getOmiyageId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>taketori.m_omiyage_lang.language</code>.
     */
    public void setLanguage(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>taketori.m_omiyage_lang.language</code>.
     */
    public String getLanguage() {
        return (String) get(1);
    }

    /**
     * Setter for <code>taketori.m_omiyage_lang.tags</code>.
     */
    public void setTags(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>taketori.m_omiyage_lang.tags</code>.
     */
    public String getTags() {
        return (String) get(2);
    }

    /**
     * Setter for <code>taketori.m_omiyage_lang.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>taketori.m_omiyage_lang.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>taketori.m_omiyage_lang.detail</code>.
     */
    public void setDetail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>taketori.m_omiyage_lang.detail</code>.
     */
    public String getDetail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>taketori.m_omiyage_lang.amount_product</code>.
     */
    public void setAmountProduct(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>taketori.m_omiyage_lang.amount_product</code>.
     */
    public String getAmountProduct() {
        return (String) get(5);
    }

    /**
     * Setter for <code>taketori.m_omiyage_lang.raw_materials</code>.
     */
    public void setRawMaterials(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>taketori.m_omiyage_lang.raw_materials</code>.
     */
    public String getRawMaterials() {
        return (String) get(6);
    }

    /**
     * Setter for <code>taketori.m_omiyage_lang.allergie</code>.
     */
    public void setAllergie(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>taketori.m_omiyage_lang.allergie</code>.
     */
    public String getAllergie() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, String, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, String, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MOmiyageLang.M_OMIYAGE_LANG.OMIYAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MOmiyageLang.M_OMIYAGE_LANG.LANGUAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MOmiyageLang.M_OMIYAGE_LANG.TAGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return MOmiyageLang.M_OMIYAGE_LANG.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return MOmiyageLang.M_OMIYAGE_LANG.DETAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MOmiyageLang.M_OMIYAGE_LANG.AMOUNT_PRODUCT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return MOmiyageLang.M_OMIYAGE_LANG.RAW_MATERIALS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return MOmiyageLang.M_OMIYAGE_LANG.ALLERGIE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getOmiyageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTags();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDetail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getAmountProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getRawMaterials();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getAllergie();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getOmiyageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTags();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDetail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAmountProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getRawMaterials();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getAllergie();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MOmiyageLangRecord value1(Integer value) {
        setOmiyageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MOmiyageLangRecord value2(String value) {
        setLanguage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MOmiyageLangRecord value3(String value) {
        setTags(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MOmiyageLangRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MOmiyageLangRecord value5(String value) {
        setDetail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MOmiyageLangRecord value6(String value) {
        setAmountProduct(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MOmiyageLangRecord value7(String value) {
        setRawMaterials(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MOmiyageLangRecord value8(String value) {
        setAllergie(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MOmiyageLangRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MOmiyageLangRecord
     */
    public MOmiyageLangRecord() {
        super(MOmiyageLang.M_OMIYAGE_LANG);
    }

    /**
     * Create a detached, initialised MOmiyageLangRecord
     */
    public MOmiyageLangRecord(Integer omiyageId, String language, String tags, String name, String detail, String amountProduct, String rawMaterials, String allergie) {
        super(MOmiyageLang.M_OMIYAGE_LANG);

        set(0, omiyageId);
        set(1, language);
        set(2, tags);
        set(3, name);
        set(4, detail);
        set(5, amountProduct);
        set(6, rawMaterials);
        set(7, allergie);
    }
}
