/*
 * This file is generated by jOOQ.
*/
package com.taketoritei.order.jooq.tables.records;


import com.taketoritei.order.jooq.tables.MOmiyage;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MOmiyageRecord extends UpdatableRecordImpl<MOmiyageRecord> implements Record8<Integer, String, String, Integer, Integer, Boolean, Timestamp, String> {

    private static final long serialVersionUID = -394089681;

    /**
     * Setter for <code>taketori.m_omiyage.omiyage_id</code>.
     */
    public void setOmiyageId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>taketori.m_omiyage.omiyage_id</code>.
     */
    public Integer getOmiyageId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>taketori.m_omiyage.category</code>.
     */
    public void setCategory(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>taketori.m_omiyage.category</code>.
     */
    public String getCategory() {
        return (String) get(1);
    }

    /**
     * Setter for <code>taketori.m_omiyage.image_ext</code>.
     */
    public void setImageExt(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>taketori.m_omiyage.image_ext</code>.
     */
    public String getImageExt() {
        return (String) get(2);
    }

    /**
     * Setter for <code>taketori.m_omiyage.price</code>.
     */
    public void setPrice(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>taketori.m_omiyage.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>taketori.m_omiyage.sort_omomi</code>.
     */
    public void setSortOmomi(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>taketori.m_omiyage.sort_omomi</code>.
     */
    public Integer getSortOmomi() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>taketori.m_omiyage.del_flg</code>.
     */
    public void setDelFlg(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>taketori.m_omiyage.del_flg</code>.
     */
    public Boolean getDelFlg() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>taketori.m_omiyage.last_date</code>.
     */
    public void setLastDate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>taketori.m_omiyage.last_date</code>.
     */
    public Timestamp getLastDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>taketori.m_omiyage.last_user</code>.
     */
    public void setLastUser(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>taketori.m_omiyage.last_user</code>.
     */
    public String getLastUser() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, Integer, Integer, Boolean, Timestamp, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, Integer, Integer, Boolean, Timestamp, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MOmiyage.M_OMIYAGE.OMIYAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MOmiyage.M_OMIYAGE.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MOmiyage.M_OMIYAGE.IMAGE_EXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return MOmiyage.M_OMIYAGE.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return MOmiyage.M_OMIYAGE.SORT_OMOMI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return MOmiyage.M_OMIYAGE.DEL_FLG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return MOmiyage.M_OMIYAGE.LAST_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return MOmiyage.M_OMIYAGE.LAST_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getOmiyageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getImageExt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getSortOmomi();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component6() {
        return getDelFlg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getLastDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getLastUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getOmiyageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getImageExt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getSortOmomi();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getDelFlg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getLastDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getLastUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MOmiyageRecord value1(Integer value) {
        setOmiyageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MOmiyageRecord value2(String value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MOmiyageRecord value3(String value) {
        setImageExt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MOmiyageRecord value4(Integer value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MOmiyageRecord value5(Integer value) {
        setSortOmomi(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MOmiyageRecord value6(Boolean value) {
        setDelFlg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MOmiyageRecord value7(Timestamp value) {
        setLastDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MOmiyageRecord value8(String value) {
        setLastUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MOmiyageRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5, Boolean value6, Timestamp value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MOmiyageRecord
     */
    public MOmiyageRecord() {
        super(MOmiyage.M_OMIYAGE);
    }

    /**
     * Create a detached, initialised MOmiyageRecord
     */
    public MOmiyageRecord(Integer omiyageId, String category, String imageExt, Integer price, Integer sortOmomi, Boolean delFlg, Timestamp lastDate, String lastUser) {
        super(MOmiyage.M_OMIYAGE);

        set(0, omiyageId);
        set(1, category);
        set(2, imageExt);
        set(3, price);
        set(4, sortOmomi);
        set(5, delFlg);
        set(6, lastDate);
        set(7, lastUser);
    }
}
