/*
 * This file is generated by jOOQ.
*/
package com.taketoritei.order.jooq.tables.records;


import com.taketoritei.order.jooq.tables.MRoom;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MRoomRecord extends TableRecordImpl<MRoomRecord> implements Record2<String, Integer> {

    private static final long serialVersionUID = 535200879;

    /**
     * Setter for <code>taketori.m_room.room_no</code>.
     */
    public void setRoomNo(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>taketori.m_room.room_no</code>.
     */
    public String getRoomNo() {
        return (String) get(0);
    }

    /**
     * Setter for <code>taketori.m_room.floor</code>.
     */
    public void setFloor(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>taketori.m_room.floor</code>.
     */
    public Integer getFloor() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return MRoom.M_ROOM.ROOM_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return MRoom.M_ROOM.FLOOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getRoomNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getFloor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getRoomNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getFloor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MRoomRecord value1(String value) {
        setRoomNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MRoomRecord value2(Integer value) {
        setFloor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MRoomRecord values(String value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MRoomRecord
     */
    public MRoomRecord() {
        super(MRoom.M_ROOM);
    }

    /**
     * Create a detached, initialised MRoomRecord
     */
    public MRoomRecord(String roomNo, Integer floor) {
        super(MRoom.M_ROOM);

        set(0, roomNo);
        set(1, floor);
    }
}
