/*
 * This file is generated by jOOQ.
*/
package com.taketoritei.order.jooq.tables.records;


import com.taketoritei.order.jooq.tables.MTimeBk;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MTimeBkRecord extends TableRecordImpl<MTimeBkRecord> implements Record6<String, String, Boolean, Boolean, String, String> {

    private static final long serialVersionUID = 1020190545;

    /**
     * Setter for <code>taketori.m_time_bk.time_cd</code>.
     */
    public void setTimeCd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>taketori.m_time_bk.time_cd</code>.
     */
    public String getTimeCd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>taketori.m_time_bk.disp_text</code>.
     */
    public void setDispText(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>taketori.m_time_bk.disp_text</code>.
     */
    public String getDispText() {
        return (String) get(1);
    }

    /**
     * Setter for <code>taketori.m_time_bk.selectable</code>.
     */
    public void setSelectable(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>taketori.m_time_bk.selectable</code>.
     */
    public Boolean getSelectable() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>taketori.m_time_bk.next_day</code>.
     */
    public void setNextDay(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>taketori.m_time_bk.next_day</code>.
     */
    public Boolean getNextDay() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>taketori.m_time_bk.hm_from</code>.
     */
    public void setHmFrom(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>taketori.m_time_bk.hm_from</code>.
     */
    public String getHmFrom() {
        return (String) get(4);
    }

    /**
     * Setter for <code>taketori.m_time_bk.hm_to</code>.
     */
    public void setHmTo(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>taketori.m_time_bk.hm_to</code>.
     */
    public String getHmTo() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, Boolean, Boolean, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, Boolean, Boolean, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return MTimeBk.M_TIME_BK.TIME_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MTimeBk.M_TIME_BK.DISP_TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return MTimeBk.M_TIME_BK.SELECTABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return MTimeBk.M_TIME_BK.NEXT_DAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return MTimeBk.M_TIME_BK.HM_FROM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MTimeBk.M_TIME_BK.HM_TO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getTimeCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getDispText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component3() {
        return getSelectable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getNextDay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getHmFrom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getHmTo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getTimeCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDispText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getSelectable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getNextDay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getHmFrom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getHmTo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MTimeBkRecord value1(String value) {
        setTimeCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MTimeBkRecord value2(String value) {
        setDispText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MTimeBkRecord value3(Boolean value) {
        setSelectable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MTimeBkRecord value4(Boolean value) {
        setNextDay(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MTimeBkRecord value5(String value) {
        setHmFrom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MTimeBkRecord value6(String value) {
        setHmTo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MTimeBkRecord values(String value1, String value2, Boolean value3, Boolean value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MTimeBkRecord
     */
    public MTimeBkRecord() {
        super(MTimeBk.M_TIME_BK);
    }

    /**
     * Create a detached, initialised MTimeBkRecord
     */
    public MTimeBkRecord(String timeCd, String dispText, Boolean selectable, Boolean nextDay, String hmFrom, String hmTo) {
        super(MTimeBk.M_TIME_BK);

        set(0, timeCd);
        set(1, dispText);
        set(2, selectable);
        set(3, nextDay);
        set(4, hmFrom);
        set(5, hmTo);
    }
}
