/*
 * This file is generated by jOOQ.
*/
package com.taketoritei.order.jooq.tables.records;


import com.taketoritei.order.jooq.tables.MTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MTimeRecord extends TableRecordImpl<MTimeRecord> implements Record7<String, String, String, Boolean, Boolean, String, String> {

    private static final long serialVersionUID = -236718210;

    /**
     * Setter for <code>taketori.m_time.time_cd</code>.
     */
    public void setTimeCd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>taketori.m_time.time_cd</code>.
     */
    public String getTimeCd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>taketori.m_time.disp_text</code>.
     */
    public void setDispText(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>taketori.m_time.disp_text</code>.
     */
    public String getDispText() {
        return (String) get(1);
    }

    /**
     * Setter for <code>taketori.m_time.bath_type</code>.
     */
    public void setBathType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>taketori.m_time.bath_type</code>.
     */
    public String getBathType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>taketori.m_time.selectable</code>.
     */
    public void setSelectable(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>taketori.m_time.selectable</code>.
     */
    public Boolean getSelectable() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>taketori.m_time.next_day</code>.
     */
    public void setNextDay(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>taketori.m_time.next_day</code>.
     */
    public Boolean getNextDay() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>taketori.m_time.hm_from</code>.
     */
    public void setHmFrom(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>taketori.m_time.hm_from</code>.
     */
    public String getHmFrom() {
        return (String) get(5);
    }

    /**
     * Setter for <code>taketori.m_time.hm_to</code>.
     */
    public void setHmTo(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>taketori.m_time.hm_to</code>.
     */
    public String getHmTo() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, Boolean, Boolean, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, Boolean, Boolean, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return MTime.M_TIME.TIME_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MTime.M_TIME.DISP_TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MTime.M_TIME.BATH_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return MTime.M_TIME.SELECTABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return MTime.M_TIME.NEXT_DAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MTime.M_TIME.HM_FROM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return MTime.M_TIME.HM_TO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getTimeCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getDispText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getBathType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getSelectable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getNextDay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getHmFrom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getHmTo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getTimeCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDispText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getBathType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getSelectable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getNextDay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getHmFrom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getHmTo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MTimeRecord value1(String value) {
        setTimeCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MTimeRecord value2(String value) {
        setDispText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MTimeRecord value3(String value) {
        setBathType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MTimeRecord value4(Boolean value) {
        setSelectable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MTimeRecord value5(Boolean value) {
        setNextDay(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MTimeRecord value6(String value) {
        setHmFrom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MTimeRecord value7(String value) {
        setHmTo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MTimeRecord values(String value1, String value2, String value3, Boolean value4, Boolean value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MTimeRecord
     */
    public MTimeRecord() {
        super(MTime.M_TIME);
    }

    /**
     * Create a detached, initialised MTimeRecord
     */
    public MTimeRecord(String timeCd, String dispText, String bathType, Boolean selectable, Boolean nextDay, String hmFrom, String hmTo) {
        super(MTime.M_TIME);

        set(0, timeCd);
        set(1, dispText);
        set(2, bathType);
        set(3, selectable);
        set(4, nextDay);
        set(5, hmFrom);
        set(6, hmTo);
    }
}
