/*
 * This file is generated by jOOQ.
*/
package com.taketoritei.order.jooq.tables.records;


import com.taketoritei.order.jooq.tables.VdCart;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VdCartRecord extends TableRecordImpl<VdCartRecord> implements Record11<Integer, String, Integer, Integer, Integer, String, Boolean, Timestamp, String, String, String> {

    private static final long serialVersionUID = -818712959;

    /**
     * Setter for <code>taketori.vd_cart.cart_id</code>.
     */
    public void setCartId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>taketori.vd_cart.cart_id</code>.
     */
    public Integer getCartId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>taketori.vd_cart.token</code>.
     */
    public void setToken(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>taketori.vd_cart.token</code>.
     */
    public String getToken() {
        return (String) get(1);
    }

    /**
     * Setter for <code>taketori.vd_cart.omiyage_id</code>.
     */
    public void setOmiyageId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>taketori.vd_cart.omiyage_id</code>.
     */
    public Integer getOmiyageId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>taketori.vd_cart.price</code>.
     */
    public void setPrice(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>taketori.vd_cart.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>taketori.vd_cart.num</code>.
     */
    public void setNum(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>taketori.vd_cart.num</code>.
     */
    public Integer getNum() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>taketori.vd_cart.cart_token</code>.
     */
    public void setCartToken(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>taketori.vd_cart.cart_token</code>.
     */
    public String getCartToken() {
        return (String) get(5);
    }

    /**
     * Setter for <code>taketori.vd_cart.del_flg</code>.
     */
    public void setDelFlg(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>taketori.vd_cart.del_flg</code>.
     */
    public Boolean getDelFlg() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>taketori.vd_cart.last_date</code>.
     */
    public void setLastDate(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>taketori.vd_cart.last_date</code>.
     */
    public Timestamp getLastDate() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>taketori.vd_cart.last_user</code>.
     */
    public void setLastUser(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>taketori.vd_cart.last_user</code>.
     */
    public String getLastUser() {
        return (String) get(8);
    }

    /**
     * Setter for <code>taketori.vd_cart.language</code>.
     */
    public void setLanguage(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>taketori.vd_cart.language</code>.
     */
    public String getLanguage() {
        return (String) get(9);
    }

    /**
     * Setter for <code>taketori.vd_cart.name</code>.
     */
    public void setName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>taketori.vd_cart.name</code>.
     */
    public String getName() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, Integer, Integer, Integer, String, Boolean, Timestamp, String, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, Integer, Integer, Integer, String, Boolean, Timestamp, String, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VdCart.VD_CART.CART_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VdCart.VD_CART.TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return VdCart.VD_CART.OMIYAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return VdCart.VD_CART.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return VdCart.VD_CART.NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return VdCart.VD_CART.CART_TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return VdCart.VD_CART.DEL_FLG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return VdCart.VD_CART.LAST_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return VdCart.VD_CART.LAST_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return VdCart.VD_CART.LANGUAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return VdCart.VD_CART.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getCartId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getOmiyageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCartToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component7() {
        return getDelFlg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getLastDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getLastUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCartId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getOmiyageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCartToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getDelFlg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getLastDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getLastUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdCartRecord value1(Integer value) {
        setCartId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdCartRecord value2(String value) {
        setToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdCartRecord value3(Integer value) {
        setOmiyageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdCartRecord value4(Integer value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdCartRecord value5(Integer value) {
        setNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdCartRecord value6(String value) {
        setCartToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdCartRecord value7(Boolean value) {
        setDelFlg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdCartRecord value8(Timestamp value) {
        setLastDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdCartRecord value9(String value) {
        setLastUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdCartRecord value10(String value) {
        setLanguage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdCartRecord value11(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdCartRecord values(Integer value1, String value2, Integer value3, Integer value4, Integer value5, String value6, Boolean value7, Timestamp value8, String value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VdCartRecord
     */
    public VdCartRecord() {
        super(VdCart.VD_CART);
    }

    /**
     * Create a detached, initialised VdCartRecord
     */
    public VdCartRecord(Integer cartId, String token, Integer omiyageId, Integer price, Integer num, String cartToken, Boolean delFlg, Timestamp lastDate, String lastUser, String language, String name) {
        super(VdCart.VD_CART);

        set(0, cartId);
        set(1, token);
        set(2, omiyageId);
        set(3, price);
        set(4, num);
        set(5, cartToken);
        set(6, delFlg);
        set(7, lastDate);
        set(8, lastUser);
        set(9, language);
        set(10, name);
    }
}
