/*
 * This file is generated by jOOQ.
*/
package com.taketoritei.order.jooq.tables.records;


import com.taketoritei.order.jooq.tables.VmOmiyage;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VmOmiyageRecord extends TableRecordImpl<VmOmiyageRecord> implements Record15<Integer, String, String, Integer, Integer, Boolean, String, String, String, String, String, String, String, Timestamp, String> {

    private static final long serialVersionUID = -575860401;

    /**
     * Setter for <code>taketori.vm_omiyage.omiyage_id</code>.
     */
    public void setOmiyageId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>taketori.vm_omiyage.omiyage_id</code>.
     */
    public Integer getOmiyageId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>taketori.vm_omiyage.category</code>.
     */
    public void setCategory(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>taketori.vm_omiyage.category</code>.
     */
    public String getCategory() {
        return (String) get(1);
    }

    /**
     * Setter for <code>taketori.vm_omiyage.image_ext</code>.
     */
    public void setImageExt(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>taketori.vm_omiyage.image_ext</code>.
     */
    public String getImageExt() {
        return (String) get(2);
    }

    /**
     * Setter for <code>taketori.vm_omiyage.price</code>.
     */
    public void setPrice(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>taketori.vm_omiyage.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>taketori.vm_omiyage.sort_omomi</code>.
     */
    public void setSortOmomi(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>taketori.vm_omiyage.sort_omomi</code>.
     */
    public Integer getSortOmomi() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>taketori.vm_omiyage.del_flg</code>.
     */
    public void setDelFlg(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>taketori.vm_omiyage.del_flg</code>.
     */
    public Boolean getDelFlg() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>taketori.vm_omiyage.language</code>.
     */
    public void setLanguage(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>taketori.vm_omiyage.language</code>.
     */
    public String getLanguage() {
        return (String) get(6);
    }

    /**
     * Setter for <code>taketori.vm_omiyage.tags</code>.
     */
    public void setTags(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>taketori.vm_omiyage.tags</code>.
     */
    public String getTags() {
        return (String) get(7);
    }

    /**
     * Setter for <code>taketori.vm_omiyage.name</code>.
     */
    public void setName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>taketori.vm_omiyage.name</code>.
     */
    public String getName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>taketori.vm_omiyage.detail</code>.
     */
    public void setDetail(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>taketori.vm_omiyage.detail</code>.
     */
    public String getDetail() {
        return (String) get(9);
    }

    /**
     * Setter for <code>taketori.vm_omiyage.amount_product</code>.
     */
    public void setAmountProduct(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>taketori.vm_omiyage.amount_product</code>.
     */
    public String getAmountProduct() {
        return (String) get(10);
    }

    /**
     * Setter for <code>taketori.vm_omiyage.raw_materials</code>.
     */
    public void setRawMaterials(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>taketori.vm_omiyage.raw_materials</code>.
     */
    public String getRawMaterials() {
        return (String) get(11);
    }

    /**
     * Setter for <code>taketori.vm_omiyage.allergie</code>.
     */
    public void setAllergie(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>taketori.vm_omiyage.allergie</code>.
     */
    public String getAllergie() {
        return (String) get(12);
    }

    /**
     * Setter for <code>taketori.vm_omiyage.last_date</code>.
     */
    public void setLastDate(Timestamp value) {
        set(13, value);
    }

    /**
     * Getter for <code>taketori.vm_omiyage.last_date</code>.
     */
    public Timestamp getLastDate() {
        return (Timestamp) get(13);
    }

    /**
     * Setter for <code>taketori.vm_omiyage.last_user</code>.
     */
    public void setLastUser(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>taketori.vm_omiyage.last_user</code>.
     */
    public String getLastUser() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, String, String, Integer, Integer, Boolean, String, String, String, String, String, String, String, Timestamp, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, String, String, Integer, Integer, Boolean, String, String, String, String, String, String, String, Timestamp, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VmOmiyage.VM_OMIYAGE.OMIYAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VmOmiyage.VM_OMIYAGE.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return VmOmiyage.VM_OMIYAGE.IMAGE_EXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return VmOmiyage.VM_OMIYAGE.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return VmOmiyage.VM_OMIYAGE.SORT_OMOMI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return VmOmiyage.VM_OMIYAGE.DEL_FLG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return VmOmiyage.VM_OMIYAGE.LANGUAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return VmOmiyage.VM_OMIYAGE.TAGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return VmOmiyage.VM_OMIYAGE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return VmOmiyage.VM_OMIYAGE.DETAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return VmOmiyage.VM_OMIYAGE.AMOUNT_PRODUCT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return VmOmiyage.VM_OMIYAGE.RAW_MATERIALS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return VmOmiyage.VM_OMIYAGE.ALLERGIE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field14() {
        return VmOmiyage.VM_OMIYAGE.LAST_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return VmOmiyage.VM_OMIYAGE.LAST_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getOmiyageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getImageExt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getSortOmomi();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component6() {
        return getDelFlg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getTags();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getDetail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getAmountProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getRawMaterials();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getAllergie();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component14() {
        return getLastDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getLastUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getOmiyageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getImageExt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getSortOmomi();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getDelFlg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getTags();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getDetail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getAmountProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getRawMaterials();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getAllergie();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value14() {
        return getLastDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getLastUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VmOmiyageRecord value1(Integer value) {
        setOmiyageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VmOmiyageRecord value2(String value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VmOmiyageRecord value3(String value) {
        setImageExt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VmOmiyageRecord value4(Integer value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VmOmiyageRecord value5(Integer value) {
        setSortOmomi(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VmOmiyageRecord value6(Boolean value) {
        setDelFlg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VmOmiyageRecord value7(String value) {
        setLanguage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VmOmiyageRecord value8(String value) {
        setTags(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VmOmiyageRecord value9(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VmOmiyageRecord value10(String value) {
        setDetail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VmOmiyageRecord value11(String value) {
        setAmountProduct(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VmOmiyageRecord value12(String value) {
        setRawMaterials(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VmOmiyageRecord value13(String value) {
        setAllergie(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VmOmiyageRecord value14(Timestamp value) {
        setLastDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VmOmiyageRecord value15(String value) {
        setLastUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VmOmiyageRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5, Boolean value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, Timestamp value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VmOmiyageRecord
     */
    public VmOmiyageRecord() {
        super(VmOmiyage.VM_OMIYAGE);
    }

    /**
     * Create a detached, initialised VmOmiyageRecord
     */
    public VmOmiyageRecord(Integer omiyageId, String category, String imageExt, Integer price, Integer sortOmomi, Boolean delFlg, String language, String tags, String name, String detail, String amountProduct, String rawMaterials, String allergie, Timestamp lastDate, String lastUser) {
        super(VmOmiyage.VM_OMIYAGE);

        set(0, omiyageId);
        set(1, category);
        set(2, imageExt);
        set(3, price);
        set(4, sortOmomi);
        set(5, delFlg);
        set(6, language);
        set(7, tags);
        set(8, name);
        set(9, detail);
        set(10, amountProduct);
        set(11, rawMaterials);
        set(12, allergie);
        set(13, lastDate);
        set(14, lastUser);
    }
}
