/*
 * This file is generated by jOOQ.
*/
package com.taketoritei.order.jooq.tables;


import com.taketoritei.order.jooq.Indexes;
import com.taketoritei.order.jooq.Keys;
import com.taketoritei.order.jooq.Taketori;
import com.taketoritei.order.jooq.tables.records.DCartRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DCart extends TableImpl<DCartRecord> {

    private static final long serialVersionUID = -1458481025;

    /**
     * The reference instance of <code>taketori.d_cart</code>
     */
    public static final DCart D_CART = new DCart();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DCartRecord> getRecordType() {
        return DCartRecord.class;
    }

    /**
     * The column <code>taketori.d_cart.cart_id</code>.
     */
    public final TableField<DCartRecord, Integer> CART_ID = createField("cart_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('d_cart_cart_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>taketori.d_cart.token</code>.
     */
    public final TableField<DCartRecord, String> TOKEN = createField("token", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>taketori.d_cart.omiyage_id</code>.
     */
    public final TableField<DCartRecord, Integer> OMIYAGE_ID = createField("omiyage_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>taketori.d_cart.price</code>.
     */
    public final TableField<DCartRecord, Integer> PRICE = createField("price", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>taketori.d_cart.num</code>.
     */
    public final TableField<DCartRecord, Integer> NUM = createField("num", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>taketori.d_cart.cart_token</code>.
     */
    public final TableField<DCartRecord, String> CART_TOKEN = createField("cart_token", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>taketori.d_cart.del_flg</code>.
     */
    public final TableField<DCartRecord, Boolean> DEL_FLG = createField("del_flg", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>taketori.d_cart.last_date</code>.
     */
    public final TableField<DCartRecord, Timestamp> LAST_DATE = createField("last_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>taketori.d_cart.last_user</code>.
     */
    public final TableField<DCartRecord, String> LAST_USER = createField("last_user", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>taketori.d_cart</code> table reference
     */
    public DCart() {
        this(DSL.name("d_cart"), null);
    }

    /**
     * Create an aliased <code>taketori.d_cart</code> table reference
     */
    public DCart(String alias) {
        this(DSL.name(alias), D_CART);
    }

    /**
     * Create an aliased <code>taketori.d_cart</code> table reference
     */
    public DCart(Name alias) {
        this(alias, D_CART);
    }

    private DCart(Name alias, Table<DCartRecord> aliased) {
        this(alias, aliased, null);
    }

    private DCart(Name alias, Table<DCartRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Taketori.TAKETORI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.D_CART_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DCartRecord, Integer> getIdentity() {
        return Keys.IDENTITY_D_CART;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DCartRecord> getPrimaryKey() {
        return Keys.D_CART_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DCartRecord>> getKeys() {
        return Arrays.<UniqueKey<DCartRecord>>asList(Keys.D_CART_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DCart as(String alias) {
        return new DCart(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DCart as(Name alias) {
        return new DCart(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DCart rename(String name) {
        return new DCart(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DCart rename(Name name) {
        return new DCart(name, null);
    }
}
