/*
 * This file is generated by jOOQ.
*/
package com.taketoritei.order.jooq.tables;


import com.taketoritei.order.jooq.Indexes;
import com.taketoritei.order.jooq.Keys;
import com.taketoritei.order.jooq.Taketori;
import com.taketoritei.order.jooq.tables.records.DOrderRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DOrder extends TableImpl<DOrderRecord> {

    private static final long serialVersionUID = -316250390;

    /**
     * The reference instance of <code>taketori.d_order</code>
     */
    public static final DOrder D_ORDER = new DOrder();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DOrderRecord> getRecordType() {
        return DOrderRecord.class;
    }

    /**
     * The column <code>taketori.d_order.order_id</code>.
     */
    public final TableField<DOrderRecord, Integer> ORDER_ID = createField("order_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('d_order_order_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>taketori.d_order.token</code>.
     */
    public final TableField<DOrderRecord, String> TOKEN = createField("token", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>taketori.d_order.omiyage_id</code>.
     */
    public final TableField<DOrderRecord, Integer> OMIYAGE_ID = createField("omiyage_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>taketori.d_order.price</code>.
     */
    public final TableField<DOrderRecord, Integer> PRICE = createField("price", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>taketori.d_order.num</code>.
     */
    public final TableField<DOrderRecord, Integer> NUM = createField("num", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>taketori.d_order.del_flg</code>.
     */
    public final TableField<DOrderRecord, Boolean> DEL_FLG = createField("del_flg", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>taketori.d_order.last_date</code>.
     */
    public final TableField<DOrderRecord, Timestamp> LAST_DATE = createField("last_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>taketori.d_order.last_user</code>.
     */
    public final TableField<DOrderRecord, String> LAST_USER = createField("last_user", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>taketori.d_order</code> table reference
     */
    public DOrder() {
        this(DSL.name("d_order"), null);
    }

    /**
     * Create an aliased <code>taketori.d_order</code> table reference
     */
    public DOrder(String alias) {
        this(DSL.name(alias), D_ORDER);
    }

    /**
     * Create an aliased <code>taketori.d_order</code> table reference
     */
    public DOrder(Name alias) {
        this(alias, D_ORDER);
    }

    private DOrder(Name alias, Table<DOrderRecord> aliased) {
        this(alias, aliased, null);
    }

    private DOrder(Name alias, Table<DOrderRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Taketori.TAKETORI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.D_ORDER_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DOrderRecord, Integer> getIdentity() {
        return Keys.IDENTITY_D_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DOrderRecord> getPrimaryKey() {
        return Keys.D_ORDER_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DOrderRecord>> getKeys() {
        return Arrays.<UniqueKey<DOrderRecord>>asList(Keys.D_ORDER_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrder as(String alias) {
        return new DOrder(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrder as(Name alias) {
        return new DOrder(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DOrder rename(String name) {
        return new DOrder(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DOrder rename(Name name) {
        return new DOrder(name, null);
    }
}
