/*
 * This file is generated by jOOQ.
*/
package com.taketoritei.order.jooq.tables;


import com.taketoritei.order.jooq.Indexes;
import com.taketoritei.order.jooq.Keys;
import com.taketoritei.order.jooq.Taketori;
import com.taketoritei.order.jooq.tables.records.MOmiyageLangRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MOmiyageLang extends TableImpl<MOmiyageLangRecord> {

    private static final long serialVersionUID = 676354465;

    /**
     * The reference instance of <code>taketori.m_omiyage_lang</code>
     */
    public static final MOmiyageLang M_OMIYAGE_LANG = new MOmiyageLang();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MOmiyageLangRecord> getRecordType() {
        return MOmiyageLangRecord.class;
    }

    /**
     * The column <code>taketori.m_omiyage_lang.omiyage_id</code>.
     */
    public final TableField<MOmiyageLangRecord, Integer> OMIYAGE_ID = createField("omiyage_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>taketori.m_omiyage_lang.language</code>.
     */
    public final TableField<MOmiyageLangRecord, String> LANGUAGE = createField("language", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>taketori.m_omiyage_lang.tags</code>.
     */
    public final TableField<MOmiyageLangRecord, String> TAGS = createField("tags", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>taketori.m_omiyage_lang.name</code>.
     */
    public final TableField<MOmiyageLangRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>taketori.m_omiyage_lang.detail</code>.
     */
    public final TableField<MOmiyageLangRecord, String> DETAIL = createField("detail", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>taketori.m_omiyage_lang.amount_product</code>.
     */
    public final TableField<MOmiyageLangRecord, String> AMOUNT_PRODUCT = createField("amount_product", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>taketori.m_omiyage_lang.raw_materials</code>.
     */
    public final TableField<MOmiyageLangRecord, String> RAW_MATERIALS = createField("raw_materials", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>taketori.m_omiyage_lang.allergie</code>.
     */
    public final TableField<MOmiyageLangRecord, String> ALLERGIE = createField("allergie", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>taketori.m_omiyage_lang</code> table reference
     */
    public MOmiyageLang() {
        this(DSL.name("m_omiyage_lang"), null);
    }

    /**
     * Create an aliased <code>taketori.m_omiyage_lang</code> table reference
     */
    public MOmiyageLang(String alias) {
        this(DSL.name(alias), M_OMIYAGE_LANG);
    }

    /**
     * Create an aliased <code>taketori.m_omiyage_lang</code> table reference
     */
    public MOmiyageLang(Name alias) {
        this(alias, M_OMIYAGE_LANG);
    }

    private MOmiyageLang(Name alias, Table<MOmiyageLangRecord> aliased) {
        this(alias, aliased, null);
    }

    private MOmiyageLang(Name alias, Table<MOmiyageLangRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Taketori.TAKETORI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.M_OMIYAGE_LANG_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MOmiyageLangRecord> getPrimaryKey() {
        return Keys.M_OMIYAGE_LANG_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MOmiyageLangRecord>> getKeys() {
        return Arrays.<UniqueKey<MOmiyageLangRecord>>asList(Keys.M_OMIYAGE_LANG_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MOmiyageLang as(String alias) {
        return new MOmiyageLang(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MOmiyageLang as(Name alias) {
        return new MOmiyageLang(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MOmiyageLang rename(String name) {
        return new MOmiyageLang(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MOmiyageLang rename(Name name) {
        return new MOmiyageLang(name, null);
    }
}
