/*
 * This file is generated by jOOQ.
*/
package com.taketoritei.order.jooq.tables;


import com.taketoritei.order.jooq.Taketori;
import com.taketoritei.order.jooq.tables.records.MTimeBkRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MTimeBk extends TableImpl<MTimeBkRecord> {

    private static final long serialVersionUID = -1541124140;

    /**
     * The reference instance of <code>taketori.m_time_bk</code>
     */
    public static final MTimeBk M_TIME_BK = new MTimeBk();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MTimeBkRecord> getRecordType() {
        return MTimeBkRecord.class;
    }

    /**
     * The column <code>taketori.m_time_bk.time_cd</code>.
     */
    public final TableField<MTimeBkRecord, String> TIME_CD = createField("time_cd", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>taketori.m_time_bk.disp_text</code>.
     */
    public final TableField<MTimeBkRecord, String> DISP_TEXT = createField("disp_text", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>taketori.m_time_bk.selectable</code>.
     */
    public final TableField<MTimeBkRecord, Boolean> SELECTABLE = createField("selectable", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>taketori.m_time_bk.next_day</code>.
     */
    public final TableField<MTimeBkRecord, Boolean> NEXT_DAY = createField("next_day", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>taketori.m_time_bk.hm_from</code>.
     */
    public final TableField<MTimeBkRecord, String> HM_FROM = createField("hm_from", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>taketori.m_time_bk.hm_to</code>.
     */
    public final TableField<MTimeBkRecord, String> HM_TO = createField("hm_to", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>taketori.m_time_bk</code> table reference
     */
    public MTimeBk() {
        this(DSL.name("m_time_bk"), null);
    }

    /**
     * Create an aliased <code>taketori.m_time_bk</code> table reference
     */
    public MTimeBk(String alias) {
        this(DSL.name(alias), M_TIME_BK);
    }

    /**
     * Create an aliased <code>taketori.m_time_bk</code> table reference
     */
    public MTimeBk(Name alias) {
        this(alias, M_TIME_BK);
    }

    private MTimeBk(Name alias, Table<MTimeBkRecord> aliased) {
        this(alias, aliased, null);
    }

    private MTimeBk(Name alias, Table<MTimeBkRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Taketori.TAKETORI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MTimeBk as(String alias) {
        return new MTimeBk(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MTimeBk as(Name alias) {
        return new MTimeBk(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MTimeBk rename(String name) {
        return new MTimeBk(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MTimeBk rename(Name name) {
        return new MTimeBk(name, null);
    }
}
