/*
 * This file is generated by jOOQ.
*/
package com.taketoritei.order.jooq.tables;


import com.taketoritei.order.jooq.Taketori;
import com.taketoritei.order.jooq.tables.records.VdOrderRecord;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VdOrder extends TableImpl<VdOrderRecord> {

    private static final long serialVersionUID = -1071355600;

    /**
     * The reference instance of <code>taketori.vd_order</code>
     */
    public static final VdOrder VD_ORDER = new VdOrder();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VdOrderRecord> getRecordType() {
        return VdOrderRecord.class;
    }

    /**
     * The column <code>taketori.vd_order.order_id</code>.
     */
    public final TableField<VdOrderRecord, Integer> ORDER_ID = createField("order_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>taketori.vd_order.token</code>.
     */
    public final TableField<VdOrderRecord, String> TOKEN = createField("token", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>taketori.vd_order.omiyage_id</code>.
     */
    public final TableField<VdOrderRecord, Integer> OMIYAGE_ID = createField("omiyage_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>taketori.vd_order.price</code>.
     */
    public final TableField<VdOrderRecord, Integer> PRICE = createField("price", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>taketori.vd_order.num</code>.
     */
    public final TableField<VdOrderRecord, Integer> NUM = createField("num", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>taketori.vd_order.del_flg</code>.
     */
    public final TableField<VdOrderRecord, Boolean> DEL_FLG = createField("del_flg", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>taketori.vd_order.last_date</code>.
     */
    public final TableField<VdOrderRecord, Timestamp> LAST_DATE = createField("last_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>taketori.vd_order.last_user</code>.
     */
    public final TableField<VdOrderRecord, String> LAST_USER = createField("last_user", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>taketori.vd_order.language</code>.
     */
    public final TableField<VdOrderRecord, String> LANGUAGE = createField("language", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>taketori.vd_order.name</code>.
     */
    public final TableField<VdOrderRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>taketori.vd_order</code> table reference
     */
    public VdOrder() {
        this(DSL.name("vd_order"), null);
    }

    /**
     * Create an aliased <code>taketori.vd_order</code> table reference
     */
    public VdOrder(String alias) {
        this(DSL.name(alias), VD_ORDER);
    }

    /**
     * Create an aliased <code>taketori.vd_order</code> table reference
     */
    public VdOrder(Name alias) {
        this(alias, VD_ORDER);
    }

    private VdOrder(Name alias, Table<VdOrderRecord> aliased) {
        this(alias, aliased, null);
    }

    private VdOrder(Name alias, Table<VdOrderRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Taketori.TAKETORI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdOrder as(String alias) {
        return new VdOrder(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdOrder as(Name alias) {
        return new VdOrder(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VdOrder rename(String name) {
        return new VdOrder(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VdOrder rename(Name name) {
        return new VdOrder(name, null);
    }
}
