/*
 * This file is generated by jOOQ.
*/
package com.taketoritei.order.jooq.tables;


import com.taketoritei.order.jooq.Taketori;
import com.taketoritei.order.jooq.tables.records.VmOmiyageRecord;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VmOmiyage extends TableImpl<VmOmiyageRecord> {

    private static final long serialVersionUID = 1819021912;

    /**
     * The reference instance of <code>taketori.vm_omiyage</code>
     */
    public static final VmOmiyage VM_OMIYAGE = new VmOmiyage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VmOmiyageRecord> getRecordType() {
        return VmOmiyageRecord.class;
    }

    /**
     * The column <code>taketori.vm_omiyage.omiyage_id</code>.
     */
    public final TableField<VmOmiyageRecord, Integer> OMIYAGE_ID = createField("omiyage_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>taketori.vm_omiyage.category</code>.
     */
    public final TableField<VmOmiyageRecord, String> CATEGORY = createField("category", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>taketori.vm_omiyage.image_ext</code>.
     */
    public final TableField<VmOmiyageRecord, String> IMAGE_EXT = createField("image_ext", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>taketori.vm_omiyage.price</code>.
     */
    public final TableField<VmOmiyageRecord, Integer> PRICE = createField("price", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>taketori.vm_omiyage.sort_omomi</code>.
     */
    public final TableField<VmOmiyageRecord, Integer> SORT_OMOMI = createField("sort_omomi", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>taketori.vm_omiyage.del_flg</code>.
     */
    public final TableField<VmOmiyageRecord, Boolean> DEL_FLG = createField("del_flg", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>taketori.vm_omiyage.language</code>.
     */
    public final TableField<VmOmiyageRecord, String> LANGUAGE = createField("language", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>taketori.vm_omiyage.tags</code>.
     */
    public final TableField<VmOmiyageRecord, String> TAGS = createField("tags", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>taketori.vm_omiyage.name</code>.
     */
    public final TableField<VmOmiyageRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>taketori.vm_omiyage.detail</code>.
     */
    public final TableField<VmOmiyageRecord, String> DETAIL = createField("detail", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>taketori.vm_omiyage.amount_product</code>.
     */
    public final TableField<VmOmiyageRecord, String> AMOUNT_PRODUCT = createField("amount_product", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>taketori.vm_omiyage.raw_materials</code>.
     */
    public final TableField<VmOmiyageRecord, String> RAW_MATERIALS = createField("raw_materials", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>taketori.vm_omiyage.allergie</code>.
     */
    public final TableField<VmOmiyageRecord, String> ALLERGIE = createField("allergie", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>taketori.vm_omiyage.last_date</code>.
     */
    public final TableField<VmOmiyageRecord, Timestamp> LAST_DATE = createField("last_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>taketori.vm_omiyage.last_user</code>.
     */
    public final TableField<VmOmiyageRecord, String> LAST_USER = createField("last_user", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>taketori.vm_omiyage</code> table reference
     */
    public VmOmiyage() {
        this(DSL.name("vm_omiyage"), null);
    }

    /**
     * Create an aliased <code>taketori.vm_omiyage</code> table reference
     */
    public VmOmiyage(String alias) {
        this(DSL.name(alias), VM_OMIYAGE);
    }

    /**
     * Create an aliased <code>taketori.vm_omiyage</code> table reference
     */
    public VmOmiyage(Name alias) {
        this(alias, VM_OMIYAGE);
    }

    private VmOmiyage(Name alias, Table<VmOmiyageRecord> aliased) {
        this(alias, aliased, null);
    }

    private VmOmiyage(Name alias, Table<VmOmiyageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Taketori.TAKETORI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VmOmiyage as(String alias) {
        return new VmOmiyage(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VmOmiyage as(Name alias) {
        return new VmOmiyage(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VmOmiyage rename(String name) {
        return new VmOmiyage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VmOmiyage rename(Name name) {
        return new VmOmiyage(name, null);
    }
}
